#!/usr/bin/env bash
## Pages standard input using empager, but filters out any and all backspaces
## first.
#
# Note: while this will work with any input, it was initially developed for
# use in paging Python help files.
#
# Copyright (C) 2018 by James MacKay.
#
#-This program is free software: you can redistribute it and/or modify
#-it under the terms of the GNU General Public License as published by
#-the Free Software Foundation, either version 3 of the License, or
#-(at your option) any later version.
#
#-This program is distributed in the hope that it will be useful,
#-but WITHOUT ANY WARRANTY; without even the implied warranty of
#-MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#-GNU General Public License for more details.
#
#-You should have received a copy of the GNU General Public License
#-along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

if [ $# -gt 0 ]
then
    echo "Too many arguments: can only page stdin." >&2
    exit 1
fi

# 'col -b' removes backspaces.
col -b </dev/stdin | empager
